/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as ApiCreditPackagesRouteImport } from './routes/api/credit-packages'
import { Route as Char123LocaleChar125AdminRouteRouteImport } from './routes/{-$locale}/admin/route'
import { Route as Char123LocaleChar125LandingRouteRouteImport } from './routes/{-$locale}/_landing/route'
import { Route as Char123LocaleChar125LoginIndexRouteImport } from './routes/{-$locale}/login/index'
import { Route as Char123LocaleChar125AdminIndexRouteImport } from './routes/{-$locale}/admin/index'
import { Route as Char123LocaleChar125LandingIndexRouteImport } from './routes/{-$locale}/_landing/index'
import { Route as ApiUserIndexRouteImport } from './routes/api/user/index'
import { Route as ApiConfigIndexRouteImport } from './routes/api/config/index'
import { Route as Char123LocaleChar125AdminUsersRouteImport } from './routes/{-$locale}/admin/users'
import { Route as Char123LocaleChar125AdminProductsRouteImport } from './routes/{-$locale}/admin/products'
import { Route as Char123LocaleChar125AdminCreditPackagesRouteImport } from './routes/{-$locale}/admin/credit-packages'
import { Route as Char123LocaleChar125AdminConfigRouteImport } from './routes/{-$locale}/admin/config'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminCreditPackagesRouteImport } from './routes/api/admin/credit-packages'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as Char123LocaleChar125LandingRoadmapIndexRouteImport } from './routes/{-$locale}/_landing/roadmap/index'
import { Route as Char123LocaleChar125LandingDocsIndexRouteImport } from './routes/{-$locale}/_landing/docs/index'
import { Route as Char123LocaleChar125LandingChatIndexRouteImport } from './routes/{-$locale}/_landing/chat/index'
import { Route as Char123LocaleChar125LandingChangelogIndexRouteImport } from './routes/{-$locale}/_landing/changelog/index'
import { Route as Char123LocaleChar125LandingBlogIndexRouteImport } from './routes/{-$locale}/_landing/blog/index'
import { Route as ApiPaymentWebhookProviderRouteImport } from './routes/api/payment/webhook.$provider'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiCreditPackagesRoute = ApiCreditPackagesRouteImport.update({
  id: '/api/credit-packages',
  path: '/api/credit-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AdminRouteRoute =
  Char123LocaleChar125AdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LandingRouteRoute =
  Char123LocaleChar125LandingRouteRouteImport.update({
    id: '/_landing',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LoginIndexRoute =
  Char123LocaleChar125LoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AdminIndexRoute =
  Char123LocaleChar125AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125LandingIndexRoute =
  Char123LocaleChar125LandingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const ApiUserIndexRoute = ApiUserIndexRouteImport.update({
  id: '/api/user/',
  path: '/api/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigIndexRoute = ApiConfigIndexRouteImport.update({
  id: '/api/config/',
  path: '/api/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AdminUsersRoute =
  Char123LocaleChar125AdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminProductsRoute =
  Char123LocaleChar125AdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminCreditPackagesRoute =
  Char123LocaleChar125AdminCreditPackagesRouteImport.update({
    id: '/credit-packages',
    path: '/credit-packages',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const Char123LocaleChar125AdminConfigRoute =
  Char123LocaleChar125AdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => Char123LocaleChar125AdminRouteRoute,
  } as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreditPackagesRoute = ApiAdminCreditPackagesRouteImport.update({
  id: '/api/admin/credit-packages',
  path: '/api/admin/credit-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125LandingRoadmapIndexRoute =
  Char123LocaleChar125LandingRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingDocsIndexRoute =
  Char123LocaleChar125LandingDocsIndexRouteImport.update({
    id: '/docs/',
    path: '/docs/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingChatIndexRoute =
  Char123LocaleChar125LandingChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingChangelogIndexRoute =
  Char123LocaleChar125LandingChangelogIndexRouteImport.update({
    id: '/changelog/',
    path: '/changelog/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const Char123LocaleChar125LandingBlogIndexRoute =
  Char123LocaleChar125LandingBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125LandingRouteRoute,
  } as any)
const ApiPaymentWebhookProviderRoute =
  ApiPaymentWebhookProviderRouteImport.update({
    id: '/api/payment/webhook/$provider',
    path: '/api/payment/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125LandingRouteRouteWithChildren
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteRouteWithChildren
  '/api/credit-packages': typeof ApiCreditPackagesRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/{-$locale}/admin/config': typeof Char123LocaleChar125AdminConfigRoute
  '/{-$locale}/admin/credit-packages': typeof Char123LocaleChar125AdminCreditPackagesRoute
  '/{-$locale}/admin/products': typeof Char123LocaleChar125AdminProductsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/api/config': typeof ApiConfigIndexRoute
  '/api/user': typeof ApiUserIndexRoute
  '/{-$locale}/': typeof Char123LocaleChar125LandingIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginIndexRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125LandingBlogIndexRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125LandingChangelogIndexRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125LandingChatIndexRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125LandingDocsIndexRoute
  '/{-$locale}/roadmap': typeof Char123LocaleChar125LandingRoadmapIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125LandingIndexRoute
  '/api/credit-packages': typeof ApiCreditPackagesRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/{-$locale}/admin/config': typeof Char123LocaleChar125AdminConfigRoute
  '/{-$locale}/admin/credit-packages': typeof Char123LocaleChar125AdminCreditPackagesRoute
  '/{-$locale}/admin/products': typeof Char123LocaleChar125AdminProductsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/api/config': typeof ApiConfigIndexRoute
  '/api/user': typeof ApiUserIndexRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginIndexRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125LandingBlogIndexRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125LandingChangelogIndexRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125LandingChatIndexRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125LandingDocsIndexRoute
  '/{-$locale}/roadmap': typeof Char123LocaleChar125LandingRoadmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/_landing': typeof Char123LocaleChar125LandingRouteRouteWithChildren
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteRouteWithChildren
  '/api/credit-packages': typeof ApiCreditPackagesRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/{-$locale}/admin/config': typeof Char123LocaleChar125AdminConfigRoute
  '/{-$locale}/admin/credit-packages': typeof Char123LocaleChar125AdminCreditPackagesRoute
  '/{-$locale}/admin/products': typeof Char123LocaleChar125AdminProductsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/api/config/': typeof ApiConfigIndexRoute
  '/api/user/': typeof ApiUserIndexRoute
  '/{-$locale}/_landing/': typeof Char123LocaleChar125LandingIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/login/': typeof Char123LocaleChar125LoginIndexRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/_landing/blog/': typeof Char123LocaleChar125LandingBlogIndexRoute
  '/{-$locale}/_landing/changelog/': typeof Char123LocaleChar125LandingChangelogIndexRoute
  '/{-$locale}/_landing/chat/': typeof Char123LocaleChar125LandingChatIndexRoute
  '/{-$locale}/_landing/docs/': typeof Char123LocaleChar125LandingDocsIndexRoute
  '/{-$locale}/_landing/roadmap/': typeof Char123LocaleChar125LandingRoadmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/admin'
    | '/api/credit-packages'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/payment/checkout'
    | '/{-$locale}/admin/config'
    | '/{-$locale}/admin/credit-packages'
    | '/{-$locale}/admin/products'
    | '/{-$locale}/admin/users'
    | '/api/config'
    | '/api/user'
    | '/{-$locale}/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/login'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/blog'
    | '/{-$locale}/changelog'
    | '/{-$locale}/chat'
    | '/{-$locale}/docs'
    | '/{-$locale}/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/api/credit-packages'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/payment/checkout'
    | '/{-$locale}/admin/config'
    | '/{-$locale}/admin/credit-packages'
    | '/{-$locale}/admin/products'
    | '/{-$locale}/admin/users'
    | '/api/config'
    | '/api/user'
    | '/{-$locale}/admin'
    | '/{-$locale}/login'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/blog'
    | '/{-$locale}/changelog'
    | '/{-$locale}/chat'
    | '/{-$locale}/docs'
    | '/{-$locale}/roadmap'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/_landing'
    | '/{-$locale}/admin'
    | '/api/credit-packages'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/payment/checkout'
    | '/{-$locale}/admin/config'
    | '/{-$locale}/admin/credit-packages'
    | '/{-$locale}/admin/products'
    | '/{-$locale}/admin/users'
    | '/api/config/'
    | '/api/user/'
    | '/{-$locale}/_landing/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/login/'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/_landing/blog/'
    | '/{-$locale}/_landing/changelog/'
    | '/{-$locale}/_landing/chat/'
    | '/{-$locale}/_landing/docs/'
    | '/{-$locale}/_landing/roadmap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  ApiCreditPackagesRoute: typeof ApiCreditPackagesRoute
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminCreditPackagesRoute: typeof ApiAdminCreditPackagesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiConfigIndexRoute: typeof ApiConfigIndexRoute
  ApiUserIndexRoute: typeof ApiUserIndexRoute
  ApiPaymentWebhookProviderRoute: typeof ApiPaymentWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/credit-packages': {
      id: '/api/credit-packages'
      path: '/api/credit-packages'
      fullPath: '/api/credit-packages'
      preLoaderRoute: typeof ApiCreditPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/admin': {
      id: '/{-$locale}/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125AdminRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_landing': {
      id: '/{-$locale}/_landing'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125LandingRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/login/': {
      id: '/{-$locale}/login/'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/admin/': {
      id: '/{-$locale}/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125AdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/_landing/': {
      id: '/{-$locale}/_landing/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125LandingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/api/user/': {
      id: '/api/user/'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config/': {
      id: '/api/config/'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/admin/users': {
      id: '/{-$locale}/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125AdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/products': {
      id: '/{-$locale}/admin/products'
      path: '/products'
      fullPath: '/{-$locale}/admin/products'
      preLoaderRoute: typeof Char123LocaleChar125AdminProductsRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/credit-packages': {
      id: '/{-$locale}/admin/credit-packages'
      path: '/credit-packages'
      fullPath: '/{-$locale}/admin/credit-packages'
      preLoaderRoute: typeof Char123LocaleChar125AdminCreditPackagesRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/{-$locale}/admin/config': {
      id: '/{-$locale}/admin/config'
      path: '/config'
      fullPath: '/{-$locale}/admin/config'
      preLoaderRoute: typeof Char123LocaleChar125AdminConfigRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRouteRoute
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/credit-packages': {
      id: '/api/admin/credit-packages'
      path: '/api/admin/credit-packages'
      fullPath: '/api/admin/credit-packages'
      preLoaderRoute: typeof ApiAdminCreditPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_landing/roadmap/': {
      id: '/{-$locale}/_landing/roadmap/'
      path: '/roadmap'
      fullPath: '/{-$locale}/roadmap'
      preLoaderRoute: typeof Char123LocaleChar125LandingRoadmapIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/docs/': {
      id: '/{-$locale}/_landing/docs/'
      path: '/docs'
      fullPath: '/{-$locale}/docs'
      preLoaderRoute: typeof Char123LocaleChar125LandingDocsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/chat/': {
      id: '/{-$locale}/_landing/chat/'
      path: '/chat'
      fullPath: '/{-$locale}/chat'
      preLoaderRoute: typeof Char123LocaleChar125LandingChatIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/changelog/': {
      id: '/{-$locale}/_landing/changelog/'
      path: '/changelog'
      fullPath: '/{-$locale}/changelog'
      preLoaderRoute: typeof Char123LocaleChar125LandingChangelogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/{-$locale}/_landing/blog/': {
      id: '/{-$locale}/_landing/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125LandingBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125LandingRouteRoute
    }
    '/api/payment/webhook/$provider': {
      id: '/api/payment/webhook/$provider'
      path: '/api/payment/webhook/$provider'
      fullPath: '/api/payment/webhook/$provider'
      preLoaderRoute: typeof ApiPaymentWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125LandingRouteRouteChildren {
  Char123LocaleChar125LandingIndexRoute: typeof Char123LocaleChar125LandingIndexRoute
  Char123LocaleChar125LandingBlogIndexRoute: typeof Char123LocaleChar125LandingBlogIndexRoute
  Char123LocaleChar125LandingChangelogIndexRoute: typeof Char123LocaleChar125LandingChangelogIndexRoute
  Char123LocaleChar125LandingChatIndexRoute: typeof Char123LocaleChar125LandingChatIndexRoute
  Char123LocaleChar125LandingDocsIndexRoute: typeof Char123LocaleChar125LandingDocsIndexRoute
  Char123LocaleChar125LandingRoadmapIndexRoute: typeof Char123LocaleChar125LandingRoadmapIndexRoute
}

const Char123LocaleChar125LandingRouteRouteChildren: Char123LocaleChar125LandingRouteRouteChildren =
  {
    Char123LocaleChar125LandingIndexRoute:
      Char123LocaleChar125LandingIndexRoute,
    Char123LocaleChar125LandingBlogIndexRoute:
      Char123LocaleChar125LandingBlogIndexRoute,
    Char123LocaleChar125LandingChangelogIndexRoute:
      Char123LocaleChar125LandingChangelogIndexRoute,
    Char123LocaleChar125LandingChatIndexRoute:
      Char123LocaleChar125LandingChatIndexRoute,
    Char123LocaleChar125LandingDocsIndexRoute:
      Char123LocaleChar125LandingDocsIndexRoute,
    Char123LocaleChar125LandingRoadmapIndexRoute:
      Char123LocaleChar125LandingRoadmapIndexRoute,
  }

const Char123LocaleChar125LandingRouteRouteWithChildren =
  Char123LocaleChar125LandingRouteRoute._addFileChildren(
    Char123LocaleChar125LandingRouteRouteChildren,
  )

interface Char123LocaleChar125AdminRouteRouteChildren {
  Char123LocaleChar125AdminConfigRoute: typeof Char123LocaleChar125AdminConfigRoute
  Char123LocaleChar125AdminCreditPackagesRoute: typeof Char123LocaleChar125AdminCreditPackagesRoute
  Char123LocaleChar125AdminProductsRoute: typeof Char123LocaleChar125AdminProductsRoute
  Char123LocaleChar125AdminUsersRoute: typeof Char123LocaleChar125AdminUsersRoute
  Char123LocaleChar125AdminIndexRoute: typeof Char123LocaleChar125AdminIndexRoute
}

const Char123LocaleChar125AdminRouteRouteChildren: Char123LocaleChar125AdminRouteRouteChildren =
  {
    Char123LocaleChar125AdminConfigRoute: Char123LocaleChar125AdminConfigRoute,
    Char123LocaleChar125AdminCreditPackagesRoute:
      Char123LocaleChar125AdminCreditPackagesRoute,
    Char123LocaleChar125AdminProductsRoute:
      Char123LocaleChar125AdminProductsRoute,
    Char123LocaleChar125AdminUsersRoute: Char123LocaleChar125AdminUsersRoute,
    Char123LocaleChar125AdminIndexRoute: Char123LocaleChar125AdminIndexRoute,
  }

const Char123LocaleChar125AdminRouteRouteWithChildren =
  Char123LocaleChar125AdminRouteRoute._addFileChildren(
    Char123LocaleChar125AdminRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125LandingRouteRoute: typeof Char123LocaleChar125LandingRouteRouteWithChildren
  Char123LocaleChar125AdminRouteRoute: typeof Char123LocaleChar125AdminRouteRouteWithChildren
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125LoginIndexRoute: typeof Char123LocaleChar125LoginIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125LandingRouteRoute:
      Char123LocaleChar125LandingRouteRouteWithChildren,
    Char123LocaleChar125AdminRouteRoute:
      Char123LocaleChar125AdminRouteRouteWithChildren,
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125404Route: Char123LocaleChar125404Route,
    Char123LocaleChar125LoginIndexRoute: Char123LocaleChar125LoginIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  ApiCreditPackagesRoute: ApiCreditPackagesRoute,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminCreditPackagesRoute: ApiAdminCreditPackagesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiConfigIndexRoute: ApiConfigIndexRoute,
  ApiUserIndexRoute: ApiUserIndexRoute,
  ApiPaymentWebhookProviderRoute: ApiPaymentWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
