/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125DocsRouteRouteImport } from './routes/{-$locale}/docs/route'
import { Route as Char123LocaleChar125MainRouteRouteImport } from './routes/{-$locale}/_main/route'
import { Route as Char123LocaleChar125LoginIndexRouteImport } from './routes/{-$locale}/login/index'
import { Route as Char123LocaleChar125DocsSplatRouteImport } from './routes/{-$locale}/docs/$'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiCreditPackagesRouteImport } from './routes/api/credit/packages'
import { Route as ApiCreditHistoryRouteImport } from './routes/api/credit/history'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminCreditPackagesRouteImport } from './routes/api/admin/credit-packages'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as Char123LocaleChar125MainAdminRouteRouteImport } from './routes/{-$locale}/_main/admin/route'
import { Route as Char123LocaleChar125MainLandingRouteRouteImport } from './routes/{-$locale}/_main/_landing/route'
import { Route as Char123LocaleChar125MainAdminIndexRouteImport } from './routes/{-$locale}/_main/admin/index'
import { Route as Char123LocaleChar125MainLandingIndexRouteImport } from './routes/{-$locale}/_main/_landing/index'
import { Route as Char123LocaleChar125MainAdminUsersRouteImport } from './routes/{-$locale}/_main/admin/users'
import { Route as Char123LocaleChar125MainAdminProductsRouteImport } from './routes/{-$locale}/_main/admin/products'
import { Route as Char123LocaleChar125MainAdminCreditPackagesRouteImport } from './routes/{-$locale}/_main/admin/credit-packages'
import { Route as Char123LocaleChar125MainAdminConfigRouteImport } from './routes/{-$locale}/_main/admin/config'
import { Route as Char123LocaleChar125MainLandingWaitlistRouteImport } from './routes/{-$locale}/_main/_landing/waitlist'
import { Route as Char123LocaleChar125MainLandingRoadmapRouteImport } from './routes/{-$locale}/_main/_landing/roadmap'
import { Route as Char123LocaleChar125MainLandingChatRouteImport } from './routes/{-$locale}/_main/_landing/chat'
import { Route as Char123LocaleChar125MainLandingChangelogRouteImport } from './routes/{-$locale}/_main/_landing/changelog'
import { Route as ApiPaymentWebhookProviderRouteImport } from './routes/api/payment/webhook.$provider'
import { Route as Char123LocaleChar125MainLandingBlogIndexRouteImport } from './routes/{-$locale}/_main/_landing/blog/index'
import { Route as Char123LocaleChar125MainLandingBlogSlugRouteImport } from './routes/{-$locale}/_main/_landing/blog/$slug'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DocsRouteRoute =
  Char123LocaleChar125DocsRouteRouteImport.update({
    id: '/docs',
    path: '/docs',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MainRouteRoute =
  Char123LocaleChar125MainRouteRouteImport.update({
    id: '/_main',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LoginIndexRoute =
  Char123LocaleChar125LoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DocsSplatRoute =
  Char123LocaleChar125DocsSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditPackagesRoute = ApiCreditPackagesRouteImport.update({
  id: '/api/credit/packages',
  path: '/api/credit/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditHistoryRoute = ApiCreditHistoryRouteImport.update({
  id: '/api/credit/history',
  path: '/api/credit/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreditPackagesRoute = ApiAdminCreditPackagesRouteImport.update({
  id: '/api/admin/credit-packages',
  path: '/api/admin/credit-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125MainAdminRouteRoute =
  Char123LocaleChar125MainAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingRouteRoute =
  Char123LocaleChar125MainLandingRouteRouteImport.update({
    id: '/_landing',
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminIndexRoute =
  Char123LocaleChar125MainAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingIndexRoute =
  Char123LocaleChar125MainLandingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminUsersRoute =
  Char123LocaleChar125MainAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminProductsRoute =
  Char123LocaleChar125MainAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminCreditPackagesRoute =
  Char123LocaleChar125MainAdminCreditPackagesRouteImport.update({
    id: '/credit-packages',
    path: '/credit-packages',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminConfigRoute =
  Char123LocaleChar125MainAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingWaitlistRoute =
  Char123LocaleChar125MainLandingWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingRoadmapRoute =
  Char123LocaleChar125MainLandingRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingChatRoute =
  Char123LocaleChar125MainLandingChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingChangelogRoute =
  Char123LocaleChar125MainLandingChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const ApiPaymentWebhookProviderRoute =
  ApiPaymentWebhookProviderRouteImport.update({
    id: '/api/payment/webhook/$provider',
    path: '/api/payment/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125MainLandingBlogIndexRoute =
  Char123LocaleChar125MainLandingBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingBlogSlugRoute =
  Char123LocaleChar125MainLandingBlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125MainLandingRouteRouteWithChildren
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/admin': typeof Char123LocaleChar125MainAdminRouteRouteWithChildren
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credit/history': typeof ApiCreditHistoryRoute
  '/api/credit/packages': typeof ApiCreditPackagesRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsSplatRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginIndexRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125MainLandingChangelogRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125MainLandingChatRoute
  '/{-$locale}/roadmap': typeof Char123LocaleChar125MainLandingRoadmapRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125MainLandingWaitlistRoute
  '/{-$locale}/admin/config': typeof Char123LocaleChar125MainAdminConfigRoute
  '/{-$locale}/admin/credit-packages': typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  '/{-$locale}/admin/products': typeof Char123LocaleChar125MainAdminProductsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125MainAdminUsersRoute
  '/{-$locale}/': typeof Char123LocaleChar125MainLandingIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125MainAdminIndexRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125MainLandingBlogSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125MainLandingBlogIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125MainLandingIndexRoute
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credit/history': typeof ApiCreditHistoryRoute
  '/api/credit/packages': typeof ApiCreditPackagesRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsSplatRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginIndexRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125MainLandingChangelogRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125MainLandingChatRoute
  '/{-$locale}/roadmap': typeof Char123LocaleChar125MainLandingRoadmapRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125MainLandingWaitlistRoute
  '/{-$locale}/admin/config': typeof Char123LocaleChar125MainAdminConfigRoute
  '/{-$locale}/admin/credit-packages': typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  '/{-$locale}/admin/products': typeof Char123LocaleChar125MainAdminProductsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125MainAdminUsersRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125MainAdminIndexRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125MainLandingBlogSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125MainLandingBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/_main': typeof Char123LocaleChar125MainRouteRouteWithChildren
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/_main/_landing': typeof Char123LocaleChar125MainLandingRouteRouteWithChildren
  '/{-$locale}/_main/admin': typeof Char123LocaleChar125MainAdminRouteRouteWithChildren
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credit/history': typeof ApiCreditHistoryRoute
  '/api/credit/packages': typeof ApiCreditPackagesRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsSplatRoute
  '/{-$locale}/login/': typeof Char123LocaleChar125LoginIndexRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/_main/_landing/changelog': typeof Char123LocaleChar125MainLandingChangelogRoute
  '/{-$locale}/_main/_landing/chat': typeof Char123LocaleChar125MainLandingChatRoute
  '/{-$locale}/_main/_landing/roadmap': typeof Char123LocaleChar125MainLandingRoadmapRoute
  '/{-$locale}/_main/_landing/waitlist': typeof Char123LocaleChar125MainLandingWaitlistRoute
  '/{-$locale}/_main/admin/config': typeof Char123LocaleChar125MainAdminConfigRoute
  '/{-$locale}/_main/admin/credit-packages': typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  '/{-$locale}/_main/admin/products': typeof Char123LocaleChar125MainAdminProductsRoute
  '/{-$locale}/_main/admin/users': typeof Char123LocaleChar125MainAdminUsersRoute
  '/{-$locale}/_main/_landing/': typeof Char123LocaleChar125MainLandingIndexRoute
  '/{-$locale}/_main/admin/': typeof Char123LocaleChar125MainAdminIndexRoute
  '/{-$locale}/_main/_landing/blog/$slug': typeof Char123LocaleChar125MainLandingBlogSlugRoute
  '/{-$locale}/_main/_landing/blog/': typeof Char123LocaleChar125MainLandingBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/docs'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/admin'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/credit/history'
    | '/api/credit/packages'
    | '/api/payment/checkout'
    | '/{-$locale}/docs/$'
    | '/{-$locale}/login'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/changelog'
    | '/{-$locale}/chat'
    | '/{-$locale}/roadmap'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/admin/config'
    | '/{-$locale}/admin/credit-packages'
    | '/{-$locale}/admin/products'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/docs'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/credit/history'
    | '/api/credit/packages'
    | '/api/payment/checkout'
    | '/{-$locale}/docs/$'
    | '/{-$locale}/login'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/changelog'
    | '/{-$locale}/chat'
    | '/{-$locale}/roadmap'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/admin/config'
    | '/{-$locale}/admin/credit-packages'
    | '/{-$locale}/admin/products'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/_main'
    | '/{-$locale}/docs'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/_main/_landing'
    | '/{-$locale}/_main/admin'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/credit/history'
    | '/api/credit/packages'
    | '/api/payment/checkout'
    | '/{-$locale}/docs/$'
    | '/{-$locale}/login/'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/_main/_landing/changelog'
    | '/{-$locale}/_main/_landing/chat'
    | '/{-$locale}/_main/_landing/roadmap'
    | '/{-$locale}/_main/_landing/waitlist'
    | '/{-$locale}/_main/admin/config'
    | '/{-$locale}/_main/admin/credit-packages'
    | '/{-$locale}/_main/admin/products'
    | '/{-$locale}/_main/admin/users'
    | '/{-$locale}/_main/_landing/'
    | '/{-$locale}/_main/admin/'
    | '/{-$locale}/_main/_landing/blog/$slug'
    | '/{-$locale}/_main/_landing/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminCreditPackagesRoute: typeof ApiAdminCreditPackagesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCreditHistoryRoute: typeof ApiCreditHistoryRoute
  ApiCreditPackagesRoute: typeof ApiCreditPackagesRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiPaymentWebhookProviderRoute: typeof ApiPaymentWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/docs': {
      id: '/{-$locale}/docs'
      path: '/docs'
      fullPath: '/{-$locale}/docs'
      preLoaderRoute: typeof Char123LocaleChar125DocsRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_main': {
      id: '/{-$locale}/_main'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125MainRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/login/': {
      id: '/{-$locale}/login/'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/docs/$': {
      id: '/{-$locale}/docs/$'
      path: '/$'
      fullPath: '/{-$locale}/docs/$'
      preLoaderRoute: typeof Char123LocaleChar125DocsSplatRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credit/packages': {
      id: '/api/credit/packages'
      path: '/api/credit/packages'
      fullPath: '/api/credit/packages'
      preLoaderRoute: typeof ApiCreditPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credit/history': {
      id: '/api/credit/history'
      path: '/api/credit/history'
      fullPath: '/api/credit/history'
      preLoaderRoute: typeof ApiCreditHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/credit-packages': {
      id: '/api/admin/credit-packages'
      path: '/api/admin/credit-packages'
      fullPath: '/api/admin/credit-packages'
      preLoaderRoute: typeof ApiAdminCreditPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_main/admin': {
      id: '/{-$locale}/_main/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminRouteRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    '/{-$locale}/_main/_landing': {
      id: '/{-$locale}/_main/_landing'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingRouteRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    '/{-$locale}/_main/admin/': {
      id: '/{-$locale}/_main/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/_landing/': {
      id: '/{-$locale}/_main/_landing/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/admin/users': {
      id: '/{-$locale}/_main/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/admin/products': {
      id: '/{-$locale}/_main/admin/products'
      path: '/products'
      fullPath: '/{-$locale}/admin/products'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminProductsRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/admin/credit-packages': {
      id: '/{-$locale}/_main/admin/credit-packages'
      path: '/credit-packages'
      fullPath: '/{-$locale}/admin/credit-packages'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminCreditPackagesRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/admin/config': {
      id: '/{-$locale}/_main/admin/config'
      path: '/config'
      fullPath: '/{-$locale}/admin/config'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminConfigRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/_landing/waitlist': {
      id: '/{-$locale}/_main/_landing/waitlist'
      path: '/waitlist'
      fullPath: '/{-$locale}/waitlist'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingWaitlistRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/roadmap': {
      id: '/{-$locale}/_main/_landing/roadmap'
      path: '/roadmap'
      fullPath: '/{-$locale}/roadmap'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingRoadmapRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/chat': {
      id: '/{-$locale}/_main/_landing/chat'
      path: '/chat'
      fullPath: '/{-$locale}/chat'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingChatRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/changelog': {
      id: '/{-$locale}/_main/_landing/changelog'
      path: '/changelog'
      fullPath: '/{-$locale}/changelog'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingChangelogRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/api/payment/webhook/$provider': {
      id: '/api/payment/webhook/$provider'
      path: '/api/payment/webhook/$provider'
      fullPath: '/api/payment/webhook/$provider'
      preLoaderRoute: typeof ApiPaymentWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_main/_landing/blog/': {
      id: '/{-$locale}/_main/_landing/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/blog/$slug': {
      id: '/{-$locale}/_main/_landing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingBlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
  }
}

interface Char123LocaleChar125MainLandingRouteRouteChildren {
  Char123LocaleChar125MainLandingChangelogRoute: typeof Char123LocaleChar125MainLandingChangelogRoute
  Char123LocaleChar125MainLandingChatRoute: typeof Char123LocaleChar125MainLandingChatRoute
  Char123LocaleChar125MainLandingRoadmapRoute: typeof Char123LocaleChar125MainLandingRoadmapRoute
  Char123LocaleChar125MainLandingWaitlistRoute: typeof Char123LocaleChar125MainLandingWaitlistRoute
  Char123LocaleChar125MainLandingIndexRoute: typeof Char123LocaleChar125MainLandingIndexRoute
  Char123LocaleChar125MainLandingBlogSlugRoute: typeof Char123LocaleChar125MainLandingBlogSlugRoute
  Char123LocaleChar125MainLandingBlogIndexRoute: typeof Char123LocaleChar125MainLandingBlogIndexRoute
}

const Char123LocaleChar125MainLandingRouteRouteChildren: Char123LocaleChar125MainLandingRouteRouteChildren =
  {
    Char123LocaleChar125MainLandingChangelogRoute:
      Char123LocaleChar125MainLandingChangelogRoute,
    Char123LocaleChar125MainLandingChatRoute:
      Char123LocaleChar125MainLandingChatRoute,
    Char123LocaleChar125MainLandingRoadmapRoute:
      Char123LocaleChar125MainLandingRoadmapRoute,
    Char123LocaleChar125MainLandingWaitlistRoute:
      Char123LocaleChar125MainLandingWaitlistRoute,
    Char123LocaleChar125MainLandingIndexRoute:
      Char123LocaleChar125MainLandingIndexRoute,
    Char123LocaleChar125MainLandingBlogSlugRoute:
      Char123LocaleChar125MainLandingBlogSlugRoute,
    Char123LocaleChar125MainLandingBlogIndexRoute:
      Char123LocaleChar125MainLandingBlogIndexRoute,
  }

const Char123LocaleChar125MainLandingRouteRouteWithChildren =
  Char123LocaleChar125MainLandingRouteRoute._addFileChildren(
    Char123LocaleChar125MainLandingRouteRouteChildren,
  )

interface Char123LocaleChar125MainAdminRouteRouteChildren {
  Char123LocaleChar125MainAdminConfigRoute: typeof Char123LocaleChar125MainAdminConfigRoute
  Char123LocaleChar125MainAdminCreditPackagesRoute: typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  Char123LocaleChar125MainAdminProductsRoute: typeof Char123LocaleChar125MainAdminProductsRoute
  Char123LocaleChar125MainAdminUsersRoute: typeof Char123LocaleChar125MainAdminUsersRoute
  Char123LocaleChar125MainAdminIndexRoute: typeof Char123LocaleChar125MainAdminIndexRoute
}

const Char123LocaleChar125MainAdminRouteRouteChildren: Char123LocaleChar125MainAdminRouteRouteChildren =
  {
    Char123LocaleChar125MainAdminConfigRoute:
      Char123LocaleChar125MainAdminConfigRoute,
    Char123LocaleChar125MainAdminCreditPackagesRoute:
      Char123LocaleChar125MainAdminCreditPackagesRoute,
    Char123LocaleChar125MainAdminProductsRoute:
      Char123LocaleChar125MainAdminProductsRoute,
    Char123LocaleChar125MainAdminUsersRoute:
      Char123LocaleChar125MainAdminUsersRoute,
    Char123LocaleChar125MainAdminIndexRoute:
      Char123LocaleChar125MainAdminIndexRoute,
  }

const Char123LocaleChar125MainAdminRouteRouteWithChildren =
  Char123LocaleChar125MainAdminRouteRoute._addFileChildren(
    Char123LocaleChar125MainAdminRouteRouteChildren,
  )

interface Char123LocaleChar125MainRouteRouteChildren {
  Char123LocaleChar125MainLandingRouteRoute: typeof Char123LocaleChar125MainLandingRouteRouteWithChildren
  Char123LocaleChar125MainAdminRouteRoute: typeof Char123LocaleChar125MainAdminRouteRouteWithChildren
}

const Char123LocaleChar125MainRouteRouteChildren: Char123LocaleChar125MainRouteRouteChildren =
  {
    Char123LocaleChar125MainLandingRouteRoute:
      Char123LocaleChar125MainLandingRouteRouteWithChildren,
    Char123LocaleChar125MainAdminRouteRoute:
      Char123LocaleChar125MainAdminRouteRouteWithChildren,
  }

const Char123LocaleChar125MainRouteRouteWithChildren =
  Char123LocaleChar125MainRouteRoute._addFileChildren(
    Char123LocaleChar125MainRouteRouteChildren,
  )

interface Char123LocaleChar125DocsRouteRouteChildren {
  Char123LocaleChar125DocsSplatRoute: typeof Char123LocaleChar125DocsSplatRoute
}

const Char123LocaleChar125DocsRouteRouteChildren: Char123LocaleChar125DocsRouteRouteChildren =
  {
    Char123LocaleChar125DocsSplatRoute: Char123LocaleChar125DocsSplatRoute,
  }

const Char123LocaleChar125DocsRouteRouteWithChildren =
  Char123LocaleChar125DocsRouteRoute._addFileChildren(
    Char123LocaleChar125DocsRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125MainRouteRoute: typeof Char123LocaleChar125MainRouteRouteWithChildren
  Char123LocaleChar125DocsRouteRoute: typeof Char123LocaleChar125DocsRouteRouteWithChildren
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125LoginIndexRoute: typeof Char123LocaleChar125LoginIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125MainRouteRoute:
      Char123LocaleChar125MainRouteRouteWithChildren,
    Char123LocaleChar125DocsRouteRoute:
      Char123LocaleChar125DocsRouteRouteWithChildren,
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125404Route: Char123LocaleChar125404Route,
    Char123LocaleChar125LoginIndexRoute: Char123LocaleChar125LoginIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminCreditPackagesRoute: ApiAdminCreditPackagesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCreditHistoryRoute: ApiCreditHistoryRoute,
  ApiCreditPackagesRoute: ApiCreditPackagesRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiPaymentWebhookProviderRoute: ApiPaymentWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
