import type { AIModelMeta } from "./types"

export const models: AIModelMeta[] = [
  // ==================== OpenAI ====================
  {
    id: "openai/gpt-4o",
    label: "GPT-4o",
    provider: "openai",
    providerModelId: "gpt-4o",
    description: "OpenAI's flagship multimodal model",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 3,
  },
  {
    id: "openai/gpt-4o-mini",
    label: "GPT-4o Mini",
    provider: "openai",
    providerModelId: "gpt-4o-mini",
    description: "OpenAI's fast and affordable model",
    capabilities: { vision: true, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
  },
  {
    id: "openai/gpt-4.1-nano",
    label: "GPT-4.1 Nano",
    provider: "openai",
    providerModelId: "gpt-4.1-nano",
    description: "OpenAI's smallest model",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
  },
  {
    id: "openai/gpt-4.1-mini",
    label: "GPT-4.1 Mini",
    provider: "openai",
    providerModelId: "gpt-4.1-mini",
    description: "OpenAI's small model",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 2,
  },
  {
    id: "openai/gpt-4.1",
    label: "GPT-4.1",
    provider: "openai",
    providerModelId: "gpt-4.1",
    description: "OpenAI's advanced model",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 5,
    isNew: true,
  },
  {
    id: "openai/gpt-5-nano",
    label: "GPT-5 Nano",
    provider: "openai",
    providerModelId: "gpt-5-nano",
    description: "OpenAI's smallest flagship LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 2,
    isNew: true,
  },
  {
    id: "openai/gpt-5-mini",
    label: "GPT-5 Mini",
    provider: "openai",
    providerModelId: "gpt-5-mini",
    description: "OpenAI's small flagship LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "openai/gpt-5",
    label: "GPT-5",
    provider: "openai",
    providerModelId: "gpt-5",
    description: "OpenAI's flagship LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 5,
    isNew: true,
  },
  {
    id: "openai/gpt-5-medium",
    label: "GPT-5 Medium",
    provider: "openai",
    providerModelId: "gpt-5",
    description: "OpenAI's flagship reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 6,
    isNew: true,
  },
  {
    id: "openai/gpt-5.1",
    label: "GPT-5.1 Instant",
    provider: "openai",
    providerModelId: "gpt-5.1",
    description: "OpenAI's fast and smart LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 5,
    isNew: true,
  },
  {
    id: "openai/gpt-5.1-thinking",
    label: "GPT-5.1 Thinking",
    provider: "openai",
    providerModelId: "gpt-5.1",
    description: "OpenAI's smart reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 6,
    isNew: true,
  },
  {
    id: "openai/gpt-5.2",
    label: "GPT-5.2 Instant",
    provider: "openai",
    providerModelId: "gpt-5.2",
    description: "OpenAI's latest and greatest LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 5,
    isNew: true,
  },
  {
    id: "openai/gpt-5.2-thinking",
    label: "GPT-5.2 Thinking",
    provider: "openai",
    providerModelId: "gpt-5.2",
    description: "OpenAI's latest and greatest reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 6,
    isNew: true,
  },
  {
    id: "openai/o3",
    label: "o3",
    provider: "openai",
    providerModelId: "o3",
    description: "OpenAI's advanced reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 6,
  },
  {
    id: "openai/o3-mini",
    label: "o3 Mini",
    provider: "openai",
    providerModelId: "o3-mini",
    description: "OpenAI's compact reasoning model",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 4,
  },
  {
    id: "openai/o4-mini",
    label: "o4 Mini",
    provider: "openai",
    providerModelId: "o4-mini",
    description: "OpenAI's latest mini reasoning model",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 4,
    isNew: true,
  },
  {
    id: "openai/gpt-5.1-codex",
    label: "GPT-5.1 Codex",
    provider: "openai",
    providerModelId: "gpt-5.1-codex",
    description: "OpenAI's advanced coding LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 6,
    isNew: true,
  },
  {
    id: "openai/gpt-5.1-codex-mini",
    label: "GPT-5.1 Codex Mini",
    provider: "openai",
    providerModelId: "gpt-5.1-codex-mini",
    description: "OpenAI's compact coding LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 5,
    isNew: true,
  },
  {
    id: "openai/gpt-5.1-codex-max",
    label: "GPT-5.1 Codex Max",
    provider: "openai",
    providerModelId: "gpt-5.1-codex-max",
    description: "OpenAI's most powerful coding LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 8,
    isNew: true,
  },
  {
    id: "openai/gpt-5-codex",
    label: "GPT-5 Codex",
    provider: "openai",
    providerModelId: "gpt-5-codex",
    description: "OpenAI's coding LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 6,
    isNew: true,
  },
  {
    id: "openai/gpt-oss-20b",
    label: "GPT OSS 20B",
    provider: "groq",
    providerModelId: "openai/gpt-oss-20b",
    description: "OpenAI's small open-source LLM via Groq",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
  },
  {
    id: "openai/gpt-oss-120b",
    label: "GPT OSS 120B",
    provider: "baseten",
    providerModelId: "openai/gpt-oss-120b",
    description: "OpenAI's advanced open-source LLM via Baseten",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 3,
  },

  // ==================== Anthropic ====================
  {
    id: "anthropic/claude-haiku-4-5",
    label: "Claude Haiku 4.5",
    provider: "anthropic",
    providerModelId: "claude-haiku-4-5",
    description: "Anthropic's fast and efficient model",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
  },
  {
    id: "anthropic/claude-sonnet-4-5",
    label: "Claude Sonnet 4.5",
    provider: "anthropic",
    providerModelId: "claude-sonnet-4-5",
    description: "Anthropic's balanced model",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 8192,
    creditCost: 4,
  },
  {
    id: "anthropic/claude-sonnet-4-5-thinking",
    label: "Claude Sonnet 4.5 Thinking",
    provider: "anthropic",
    providerModelId: "claude-sonnet-4-5",
    description: "Claude Sonnet 4.5 with extended thinking",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 6,
  },
  {
    id: "anthropic/claude-opus-4-5",
    label: "Claude Opus 4.5",
    provider: "anthropic",
    providerModelId: "claude-opus-4-5",
    description: "Anthropic's most capable model",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 8192,
    creditCost: 8,
    isNew: true,
  },
  {
    id: "anthropic/claude-opus-4-5-thinking",
    label: "Claude Opus 4.5 Thinking",
    provider: "anthropic",
    providerModelId: "claude-opus-4-5",
    description: "Claude Opus 4.5 with extended thinking",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 10,
    isNew: true,
  },

  // ==================== Google ====================
  {
    id: "google/gemini-2.0-flash-lite",
    label: "Gemini 2.0 Flash Lite",
    provider: "google",
    providerModelId: "gemini-2.0-flash-lite",
    description: "Google's lightweight fast model",
    capabilities: { vision: true, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
  },
  {
    id: "google/gemini-2.0-flash",
    label: "Gemini 2.0 Flash",
    provider: "google",
    providerModelId: "gemini-2.0-flash",
    description: "Google's balanced speed and quality model",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
  },
  {
    id: "google/gemini-2.5-flash-lite",
    label: "Gemini 2.5 Flash Lite",
    provider: "google",
    providerModelId: "gemini-flash-lite-latest",
    description: "Google's advanced small LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 10000,
    creditCost: 1,
    isNew: true,
  },
  {
    id: "google/gemini-2.5-flash",
    label: "Gemini 2.5 Flash",
    provider: "google",
    providerModelId: "gemini-flash-latest",
    description: "Google's advanced small LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 2,
    isNew: true,
  },
  {
    id: "google/gemini-2.5-flash-thinking",
    label: "Gemini 2.5 Flash Thinking",
    provider: "google",
    providerModelId: "gemini-flash-latest",
    description: "Google's advanced small LLM with thinking",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "google/gemini-2.5-pro",
    label: "Gemini 2.5 Pro",
    provider: "google",
    providerModelId: "gemini-2.5-pro",
    description: "Google's advanced LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 5,
    isNew: true,
  },
  {
    id: "google/gemini-2.5-pro-thinking",
    label: "Gemini 2.5 Pro Thinking",
    provider: "google",
    providerModelId: "gemini-2.5-pro",
    description: "Google's advanced LLM with thinking",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 6,
    isNew: true,
  },
  {
    id: "google/gemini-3-flash",
    label: "Gemini 3 Flash",
    provider: "google",
    providerModelId: "gemini-3-flash-preview",
    description: "Google's latest small SOTA LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "google/gemini-3-flash-thinking",
    label: "Gemini 3 Flash Thinking",
    provider: "google",
    providerModelId: "gemini-3-flash-preview",
    description: "Google's latest small SOTA LLM with thinking",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 4,
    isNew: true,
  },
  {
    id: "google/gemini-3-pro",
    label: "Gemini 3 Pro",
    provider: "google",
    providerModelId: "gemini-3-pro-preview",
    description: "Google's latest SOTA LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 6,
    isNew: true,
  },

  // ==================== xAI ====================
  {
    id: "xai/grok-3-mini",
    label: "Grok 3 Mini",
    provider: "xai",
    providerModelId: "grok-3-mini",
    description: "xAI's smallest reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "free",
    maxOutputTokens: 16000,
    creditCost: 1,
  },
  {
    id: "xai/grok-3",
    label: "Grok 3",
    provider: "xai",
    providerModelId: "grok-3",
    description: "xAI's intelligent LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 4,
  },
  {
    id: "xai/grok-3-fast",
    label: "Grok 3 Fast",
    provider: "xai",
    providerModelId: "grok-3-fast",
    description: "xAI's fast model",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 16000,
    creditCost: 1,
  },
  {
    id: "xai/grok-4",
    label: "Grok 4",
    provider: "xai",
    providerModelId: "grok-4",
    description: "xAI's most intelligent LLM",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 6,
  },
  {
    id: "xai/grok-4-fast",
    label: "Grok 4 Fast",
    provider: "xai",
    providerModelId: "grok-4-fast-non-reasoning",
    description: "xAI's fast multimodal LLM",
    capabilities: { vision: true, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 30000,
    creditCost: 1,
    isNew: true,
  },
  {
    id: "xai/grok-4-fast-thinking",
    label: "Grok 4 Fast Thinking",
    provider: "xai",
    providerModelId: "grok-4-fast",
    description: "xAI's fast multimodal reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "free",
    maxOutputTokens: 30000,
    creditCost: 2,
    isNew: true,
    parameters: { maxOutputTokens: 30000 },
  },
  {
    id: "xai/grok-4.1-fast",
    label: "Grok 4.1 Fast",
    provider: "xai",
    providerModelId: "grok-4-1-fast-non-reasoning",
    description: "xAI's greatest and fastest multimodal LLM",
    capabilities: { vision: true, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 30000,
    creditCost: 1,
    isNew: true,
  },
  {
    id: "xai/grok-4.1-fast-thinking",
    label: "Grok 4.1 Fast Thinking",
    provider: "xai",
    providerModelId: "grok-4-1-fast",
    description: "xAI's greatest and fastest multimodal reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "free",
    maxOutputTokens: 30000,
    creditCost: 2,
    isNew: true,
  },
  {
    id: "xai/grok-code",
    label: "Grok Code",
    provider: "xai",
    providerModelId: "grok-code-fast-1",
    description: "xAI's advanced coding LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 3,
  },

  // ==================== Groq ====================
  {
    id: "groq/llama-3.3-70b",
    label: "Llama 3.3 70B",
    provider: "groq",
    providerModelId: "llama-3.3-70b-versatile",
    description: "Meta's open-source model via Groq",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
  },
  {
    id: "groq/llama-3.1-8b",
    label: "Llama 3.1 8B",
    provider: "groq",
    providerModelId: "llama-3.1-8b-instant",
    description: "Meta's lightweight model via Groq",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
  },
  {
    id: "groq/qwen-qwq-32b",
    label: "QwQ 32B",
    provider: "groq",
    providerModelId: "qwen-qwq-32b",
    description: "Alibaba's reasoning model via Groq",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
    parameters: { temperature: 0.6, topP: 0.95, topK: 20 },
  },
  {
    id: "groq/qwen3-32b",
    label: "Qwen 3 32B",
    provider: "groq",
    providerModelId: "qwen/qwen3-32b",
    description: "Alibaba's base LLM via Groq",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 40960,
    creditCost: 1,
    parameters: { temperature: 0.7, topP: 0.8, topK: 20 },
  },
  {
    id: "groq/kimi-k2",
    label: "Kimi K2 (Groq)",
    provider: "groq",
    providerModelId: "moonshotai/kimi-k2-instruct-0905",
    description: "MoonShot AI's model via Groq",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 10000,
    creditCost: 1,
  },

  // ==================== Mistral ====================
  {
    id: "mistral/ministral-3b",
    label: "Ministral 3 3B",
    provider: "mistral",
    providerModelId: "ministral-3b-2512",
    description: "Mistral's mini-model 3B multimodal LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
    isNew: true,
  },
  {
    id: "mistral/ministral-8b",
    label: "Ministral 3 8B",
    provider: "mistral",
    providerModelId: "ministral-8b-2512",
    description: "Mistral's mini-model 8B multimodal LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
    isNew: true,
  },
  {
    id: "mistral/ministral-14b",
    label: "Ministral 3 14B",
    provider: "mistral",
    providerModelId: "ministral-14b-2512",
    description: "Mistral's mini-model 14B multimodal LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 2,
    isNew: true,
  },
  {
    id: "mistral/mistral-small",
    label: "Mistral Small",
    provider: "mistral",
    providerModelId: "mistral-small-latest",
    description: "Mistral's efficient model",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
  },
  {
    id: "mistral/mistral-medium",
    label: "Mistral Medium",
    provider: "mistral",
    providerModelId: "mistral-medium-2508",
    description: "Mistral's medium multimodal LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "mistral/mistral-large",
    label: "Mistral Large 3",
    provider: "mistral",
    providerModelId: "mistral-large-2512",
    description: "Mistral's latest and greatest large multimodal LLM",
    capabilities: { vision: true, reasoning: false, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 4,
    isNew: true,
  },
  {
    id: "mistral/magistral-small",
    label: "Magistral Small",
    provider: "mistral",
    providerModelId: "magistral-small-2509",
    description: "Mistral's small reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "mistral/magistral-medium",
    label: "Magistral Medium",
    provider: "mistral",
    providerModelId: "magistral-medium-2509",
    description: "Mistral's medium reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: true },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 4,
    isNew: true,
  },
  {
    id: "mistral/codestral",
    label: "Codestral",
    provider: "mistral",
    providerModelId: "codestral-latest",
    description: "Mistral's coding-focused model",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 2,
  },
  {
    id: "mistral/devstral",
    label: "Devstral 2",
    provider: "mistral",
    providerModelId: "devstral-2512",
    description: "Mistral's coding-focused LLM",
    capabilities: { vision: false, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
    isNew: true,
  },
  {
    id: "mistral/devstral-small",
    label: "Devstral Small 2",
    provider: "mistral",
    providerModelId: "labs-devstral-small-2512",
    description: "Mistral's small coding-focused LLM",
    capabilities: { vision: false, reasoning: false, pdf: true },
    tier: "free",
    maxOutputTokens: 16384,
    creditCost: 1,
    isNew: true,
  },

  // ==================== Cohere ====================
  {
    id: "cohere/command-a",
    label: "Command A",
    provider: "cohere",
    providerModelId: "command-a-03-2025",
    description: "Cohere's advanced command LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "cohere/command-a-thinking",
    label: "Command A Thinking",
    provider: "cohere",
    providerModelId: "command-a-reasoning-08-2025",
    description: "Cohere's advanced command LLM with thinking",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 4,
    isNew: true,
  },
  {
    id: "cohere/command-r-plus",
    label: "Command R+",
    provider: "cohere",
    providerModelId: "command-r-plus",
    description: "Cohere's powerful generation model",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 4096,
    creditCost: 2,
  },

  // ==================== DeepSeek ====================
  {
    id: "deepseek/deepseek-chat",
    label: "DeepSeek Chat",
    provider: "deepseek",
    providerModelId: "deepseek-chat",
    description: "DeepSeek's chat model (direct API)",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
    parameters: { temperature: 0.7, topP: 0.8 },
  },
  {
    id: "deepseek/deepseek-reasoner",
    label: "DeepSeek Reasoner",
    provider: "deepseek",
    providerModelId: "deepseek-reasoner",
    description: "DeepSeek's reasoning model (direct API)",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16384,
    creditCost: 3,
  },
  {
    id: "deepseek/deepseek-v3",
    label: "DeepSeek V3",
    provider: "baseten",
    providerModelId: "deepseek-ai/DeepSeek-V3-0324",
    description: "DeepSeek's previous advanced chat LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 2,
    parameters: { temperature: 0.7, topP: 0.8, topK: 20 },
  },
  {
    id: "deepseek/deepseek-v3.1-terminus",
    label: "DeepSeek V3.1 Terminus",
    provider: "novita",
    providerModelId: "deepseek/deepseek-v3.1-terminus",
    description: "DeepSeek's advanced chat LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 2,
    isNew: true,
    parameters: { temperature: 0.7, topP: 0.8, topK: 20 },
  },
  {
    id: "deepseek/deepseek-v3.2",
    label: "DeepSeek V3.2",
    provider: "novita",
    providerModelId: "deepseek/deepseek-v3.2",
    description: "DeepSeek's latest chat LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 2,
    isNew: true,
    parameters: { temperature: 1.0, topP: 0.95 },
  },
  {
    id: "deepseek/deepseek-v3.2-thinking",
    label: "DeepSeek V3.2 Thinking",
    provider: "novita",
    providerModelId: "deepseek/deepseek-v3.2-thinking",
    description: "DeepSeek's latest chat LLM with thinking",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "deepseek/deepseek-v3.2-exp",
    label: "DeepSeek V3.2 Exp",
    provider: "novita",
    providerModelId: "deepseek/deepseek-v3.2-exp",
    description: "DeepSeek's experimental chat LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 2,
    isNew: true,
  },
  {
    id: "deepseek/deepseek-v3.2-exp-thinking",
    label: "DeepSeek V3.2 Exp Thinking",
    provider: "novita",
    providerModelId: "deepseek/deepseek-v3.2-exp-thinking",
    description: "DeepSeek's experimental chat LLM with thinking",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "deepseek/deepseek-r1-turbo",
    label: "DeepSeek R1",
    provider: "novita",
    providerModelId: "deepseek/deepseek-r1-turbo",
    description: "DeepSeek's advanced reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 3,
    isNew: true,
  },
  {
    id: "deepseek/deepseek-r1-0528",
    label: "DeepSeek R1 0528",
    provider: "novita",
    providerModelId: "deepseek/deepseek-r1-0528",
    description: "DeepSeek's advanced reasoning LLM (0528)",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 3,
    isNew: true,
  },

  // ==================== Qwen ====================
  {
    id: "qwen/qwen3-4b",
    label: "Qwen 3 4B",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-4B-Instruct-2507:nscale",
    description: "Alibaba's small base LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 16000,
    creditCost: 1,
    parameters: { temperature: 0.7, topP: 0.8, topK: 20 },
  },
  {
    id: "qwen/qwen3-4b-thinking",
    label: "Qwen 3 4B Thinking",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-4B-Thinking-2507:nscale",
    description: "Alibaba's small reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "free",
    maxOutputTokens: 16000,
    creditCost: 1,
    parameters: { temperature: 0.6, topP: 0.95, topK: 20 },
  },
  {
    id: "qwen/qwen3-30b",
    label: "Qwen 3 30B A3B",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-30B-A3B-Instruct-2507:nebius",
    description: "Alibaba's medium instruct LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 16000,
    creditCost: 1,
    parameters: { temperature: 0.7, topP: 0.8 },
  },
  {
    id: "qwen/qwen3-30b-thinking",
    label: "Qwen 3 30B A3B Thinking",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-30B-A3B-Thinking-2507:nebius",
    description: "Alibaba's medium reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "free",
    maxOutputTokens: 16000,
    creditCost: 1,
    parameters: { temperature: 0.6, topP: 0.95 },
  },
  {
    id: "qwen/qwen3-coder-30b",
    label: "Qwen 3 Coder 30B",
    provider: "novita",
    providerModelId: "qwen/qwen3-coder-30b-a3b-instruct",
    description: "Alibaba's small coding LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 2,
    isNew: true,
    parameters: { temperature: 0.7, topP: 0.8, topK: 20 },
  },
  {
    id: "qwen/qwen3-coder-480b",
    label: "Qwen 3 Coder",
    provider: "baseten",
    providerModelId: "Qwen/Qwen3-Coder-480B-A35B-Instruct",
    description: "Alibaba's advanced coding LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 130000,
    creditCost: 5,
  },
  {
    id: "qwen/qwen3-vl-30b",
    label: "Qwen 3 VL 30B",
    provider: "novita",
    providerModelId: "qwen/qwen3-vl-30b-a3b-instruct",
    description: "Alibaba's advanced vision LLM",
    capabilities: { vision: true, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 130000,
    creditCost: 2,
    parameters: { temperature: 0.7, topP: 0.8, topK: 20 },
  },
  {
    id: "qwen/qwen3-vl-30b-thinking",
    label: "Qwen 3 VL 30B Thinking",
    provider: "novita",
    providerModelId: "qwen/qwen3-vl-30b-a3b-thinking",
    description: "Alibaba's advanced vision LLM with thinking",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 130000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 0.7, topP: 0.8, topK: 20 },
  },
  {
    id: "qwen/qwen3-next-80b",
    label: "Qwen 3 Next 80B A3B",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-Next-80B-A3B-Instruct:hyperbolic",
    description: "Qwen's advanced instruct LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 100000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 0.7, topP: 0.8 },
  },
  {
    id: "qwen/qwen3-next-80b-thinking",
    label: "Qwen 3 Next 80B A3B Thinking",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-Next-80B-A3B-Thinking:hyperbolic",
    description: "Qwen's advanced thinking LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 100000,
    creditCost: 4,
    isNew: true,
    parameters: { temperature: 0.6, topP: 0.95 },
  },
  {
    id: "qwen/qwen3-max",
    label: "Qwen 3 Max",
    provider: "novita",
    providerModelId: "qwen/qwen3-max",
    description: "Qwen's advanced instruct LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 4,
    isNew: true,
  },
  {
    id: "qwen/qwen3-235b",
    label: "Qwen 3 235B A22B",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-235B-A22B-Instruct-2507:fireworks-ai",
    description: "Qwen's advanced instruct LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 100000,
    creditCost: 4,
    parameters: { temperature: 0.7, topP: 0.8 },
  },
  {
    id: "qwen/qwen3-235b-thinking",
    label: "Qwen 3 235B A22B Thinking",
    provider: "huggingface",
    providerModelId: "Qwen/Qwen3-235B-A22B-Thinking-2507:fireworks-ai",
    description: "Qwen's advanced thinking LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 100000,
    creditCost: 5,
    parameters: { temperature: 0.6, topP: 0.95 },
  },
  {
    id: "qwen/qwen3-vl-235b",
    label: "Qwen 3 VL 235B A22B",
    provider: "novita",
    providerModelId: "qwen/qwen3-vl-235b-a22b-instruct",
    description: "Qwen's advanced vision LLM",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 4,
    isNew: true,
    parameters: { temperature: 0.6, topP: 0.95 },
  },
  {
    id: "qwen/qwen3-vl-235b-thinking",
    label: "Qwen 3 VL 235B A22B Thinking",
    provider: "novita",
    providerModelId: "qwen/qwen3-vl-235b-a22b-thinking",
    description: "Qwen's advanced vision LLM with thinking",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 5,
    isNew: true,
    parameters: { temperature: 0.6, topP: 0.95 },
  },

  // ==================== GLM / Zhipu ====================
  {
    id: "glm/glm-4.5-air",
    label: "GLM 4.5 Air",
    provider: "novita",
    providerModelId: "zai-org/glm-4.5-air",
    description: "Zhipu AI's efficient base LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 130000,
    creditCost: 2,
    parameters: { temperature: 0.6, topP: 0.95 },
  },
  {
    id: "glm/glm-4.5",
    label: "GLM 4.5",
    provider: "novita",
    providerModelId: "zai-org/glm-4.5",
    description: "Zhipu AI's advanced LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 13000,
    creditCost: 3,
    parameters: { temperature: 0.6, topP: 0.95 },
  },
  {
    id: "glm/glm-4.6",
    label: "GLM 4.6",
    provider: "huggingface",
    providerModelId: "zai-org/GLM-4.6:cerebras",
    description: "Zhipu AI's advanced reasoning LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 20000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 0.6, topP: 0.95 },
  },
  {
    id: "glm/glm-4.6v-flash",
    label: "GLM 4.6V Flash",
    provider: "huggingface",
    providerModelId: "zai-org/GLM-4.6V-Flash:zai-org",
    description: "Zhipu AI's fast vision reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "free",
    maxOutputTokens: 20000,
    creditCost: 1,
    isNew: true,
    parameters: { temperature: 0.8, topP: 0.6, topK: 2, frequencyPenalty: 1.1 },
  },
  {
    id: "glm/glm-4.6v",
    label: "GLM 4.6V",
    provider: "huggingface",
    providerModelId: "zai-org/GLM-4.6V:zai-org",
    description: "Zhipu AI's advanced vision reasoning LLM",
    capabilities: { vision: true, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 20000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 0.8, topP: 0.6, topK: 2, frequencyPenalty: 1.1 },
  },
  {
    id: "glm/glm-4.7",
    label: "GLM 4.7",
    provider: "baseten",
    providerModelId: "zai-org/GLM-4.7",
    description: "Zhipu AI's latest advanced reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 20000,
    creditCost: 4,
    isNew: true,
    parameters: { temperature: 1, topP: 0.95 },
  },

  // ==================== MiniMax ====================
  {
    id: "minimax/minimax-m1-80k",
    label: "MiniMax M1 80K",
    provider: "novita",
    providerModelId: "minimaxai/minimax-m1-80k",
    description: "MiniMax's advanced reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 0.6 },
  },
  {
    id: "minimax/minimax-m2",
    label: "MiniMax M2",
    provider: "novita",
    providerModelId: "minimaxai/minimax-m2",
    description: "MiniMax's advanced reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 1.0, topP: 0.95, topK: 40 },
  },
  {
    id: "minimax/minimax-m2.1",
    label: "MiniMax M2.1",
    provider: "novita",
    providerModelId: "minimaxai/minimax-m2.1",
    description: "MiniMax's latest advanced reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 1.0, topP: 0.95, topK: 40 },
  },
  {
    id: "minimax/minimax-m2.1-lightning",
    label: "MiniMax M2.1 Lightning",
    provider: "novita",
    providerModelId: "minimaxai/minimax-m2.1-lightning",
    description: "MiniMax's fast advanced reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 2,
    isNew: true,
    parameters: { temperature: 1.0, topP: 0.95, topK: 40 },
  },

  // ==================== Kimi / MoonShot ====================
  {
    id: "kimi/kimi-k2",
    label: "Kimi K2 Latest",
    provider: "baseten",
    providerModelId: "moonshotai/Kimi-K2-Instruct-0905",
    description: "MoonShot AI's advanced base LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 2,
    parameters: { temperature: 0.6 },
  },
  {
    id: "kimi/kimi-k2-thinking",
    label: "Kimi K2 Thinking",
    provider: "baseten",
    providerModelId: "moonshotai/Kimi-K2-Thinking",
    description: "MoonShot AI's advanced reasoning LLM",
    capabilities: { vision: false, reasoning: true, pdf: false },
    tier: "pro",
    maxOutputTokens: 10000,
    creditCost: 3,
    isNew: true,
    parameters: { temperature: 1 },
  },

  // ==================== Others ====================
  {
    id: "novita/kat-coder",
    label: "KAT-Coder-Pro V1",
    provider: "novita",
    providerModelId: "kat-coder",
    description: "Kwaipilot's advanced coding LLM",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 2,
    isNew: true,
  },
  {
    id: "novita/mimo-v2-flash",
    label: "Mimo V2 Flash",
    provider: "novita",
    providerModelId: "xiaomimimo/mimo-v2-flash",
    description: "Xiaomi's fast Mimo V2 Flash model",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "pro",
    maxOutputTokens: 16000,
    creditCost: 2,
    isNew: true,
  },

  // SiliconFlow
  {
    id: "siliconflow/deepseek-v3",
    label: "DeepSeek V3 (SiliconFlow)",
    provider: "siliconflow",
    providerModelId: "deepseek-ai/DeepSeek-V3",
    description: "DeepSeek V3 via SiliconFlow inference",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
  },
  {
    id: "siliconflow/qwen-2.5-72b",
    label: "Qwen 2.5 72B (SiliconFlow)",
    provider: "siliconflow",
    providerModelId: "Qwen/Qwen2.5-72B-Instruct",
    description: "Alibaba's model via SiliconFlow inference",
    capabilities: { vision: false, reasoning: false, pdf: false },
    tier: "free",
    maxOutputTokens: 8192,
    creditCost: 1,
  },
]
